#!/bin/bash

# This script gets the CPU usage in percent.

cpuFile="/tmp/.cpu_usage"

get_cpu() {
	if [[ -f "${cpuFile}" ]]; then
		PREV_TOTAL=$( (head -n 1) < ${cpuFile} )
		PREV_IDLE=$( (tail -n 1) < ${cpuFile} )
	fi

	CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
	unset CPU[0]                          # Discard the "cpu" prefix.
	IDLE=${CPU[4]}                        # Get the idle CPU time.

	# Calculate the total CPU time.
	TOTAL=0

	for VALUE in "${CPU[@]}"; do
		(( TOTAL += VALUE ))
	done

	if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
		# Calculate the CPU usage since we last checked.
		(( DIFF_IDLE = IDLE - PREV_IDLE ))
		(( DIFF_TOTAL = TOTAL - PREV_TOTAL ))
		(( DIFF_USAGE = (1000 * (DIFF_TOTAL - DIFF_IDLE) / DIFF_TOTAL + 5) / 10 ))
		printf "%s\n" "${DIFF_USAGE}"
	else
		printf "%s\n" "?"
	fi

	# Store the total and idle CPU times for the next check.
	printf "%s\n" "${TOTAL}" > "${cpuFile}"
	printf "%s\n" "${IDLE}" >> "${cpuFile}"
}
get_cpu
